### ISSUE TITLE
Fedora 26 does not boot with dbus-broker

### ISSUE THREAD

**Issue by godsic** [bus1/dbus-broker#29]
Once dbus-broker is enabled for root and users, Fedora 26 does not boot anymore. 

The following messages appear in the log:

Aug 23 21:27:28 xxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: dbus.socket: Failed to listen on sockets: Permission denied
Aug 23 21:27:28 xxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: dbus-broker.service: Job dbus-broker.service/start failed with result 'dependency'.
Aug 23 21:27:28 xxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: dbus.socket: Unit entered failed state.
Aug 23 21:27:28 xxxxxxxxxxxxxxxxxxxxxxxxxxx libvirtd[778]: 2017-08-23 19:27:28.641+0000: 799: error : virDBusGetSystemBus:109 : internal error: Unable to get DBus system bus connection: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Aug 23 21:27:28 xxxxxxxxxxxxxxxxxxxxxxxxxxx libvirtd[778]: 2017-08-23 19:27:28.642+0000: 799: warning : networkStateInitialize:787 : DBus not available, disabling firewalld support in bridge_network_driver: internal error: Unable to get DBus system bus connection: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Aug 23 21:27:56 xxxxxxxxxxxxxxxxxxxxxxxxxxx libvirtd[778]: 2017-08-23 19:27:56.573+0000: 778: error : virDBusGetSystemBus:109 : internal error: Unable to get DBus system bus connection: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

**Comment by michich** [comment]
Possibly a SELinux issue. Boot with `enforcing=0`.
Do you use dbus-broker-git from the COPR? Fix the labeling: `fixfiles -v -R dbus-broker-git restore`

**Comment by EduRam** [comment]
My Fedora 26 VM, boot with dbus-broker-git, without a problem.

**Comment by dvdhrm** [comment]
Booting with `enforcing=0` will "fix" the issue.

I wonder what is going on there, though. In case you used the `-git` package, then please try again with current master. We fixed a re-label issue there (https://github.com/bus1/dbus-broker/commit/d7212a265fae4222300c67b804f7ff5e6a93bc1c).

The error code suggests systemd is no longer able to listen on the dbus-socket. However, we don't touch that socket at all in the dbus-broker package. The socket is provided by dbus-daemon...

@teg, any ideas?

**Comment by dvdhrm** [comment]
Btw., the related AVC message is:

```
audit[1]: AVC avc:  denied  { create } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=unix_stream_socket permissive=0
```

This really looks like the relabeling issue michich described.

**Comment by chdongsh** [comment]
In fedora rawhide, after installing the last git dbus-broker, login service, account service etc. still failed to start, I can't boot fedora rawhide, enforcing=0 don't work. nvidia proprietary driver is installed.

**Comment by chdongsh** [comment]
[meson-log.txt](https://github.com/bus1/dbus-broker/files/1253669/meson-log.txt)
[testlog.txt](https://github.com/bus1/dbus-broker/files/1253670/testlog.txt) here are my compiling log, wish they help. "Dependency libdbus-typenum found: NO" , is libdbus-typenum important?

**Comment by chdongsh** [comment]
using meson --prefix /usr, dbus-broker works for me

**Comment by dvdhrm** [comment]
Both bugs are fixed upstream in -master. Please re-open, if this still affects you.

Thanks for the reports!
