### ISSUE TITLE
Incompatibility with the Dropbox client

### ISSUE THREAD

**Issue by karolpiczak** [bus1/dbus-broker#370]
I have encountered the same issue with the Dropbox client for Linux on Fedora 40 as described [here](https://omid.dev/2024/06/12/dropbox-tray-icon-connecting/) and [here](https://www.dropboxforum.com/t5/Apps-and-Installations/Dropbox-hung-on-connecting-Arch-Linux/td-p/749099), i.e. the tray icon menu hangs with a "Connecting..." status, without populating the submenus with additional information.

I have confirmed that replacing `dbus-broker` with `dbus-daemon` does indeed fix the issue. I would like to keep using `dbus-broker` without sacrificing this functionality. Any hints on the best way to debug this?

**Comment by dvdhrm** [comment]
I thought this was fixed by f805f4114f33ddb61382f7d6989cc3f94e0f7f1a, but I never confirmed. I will try to verify!

**Comment by zquestz** [comment]
Ahh but no release with this included!

**Comment by OndraM** [comment]
Hi, I just tried with the latest master using `dbus-broker-git` from AUR, but it does not seem to fix the issue with Dropbox client.

**Comment by dvdhrm** [comment]
This should be fixed with `Dropbox Desktop Client Stable Build 219.4.4463` (also see https://www.dropboxforum.com/discussions/101003016/stable-build-219-4-4463/824937). My tests confirm that it indeed works now.

I have contacted the developers to get information on what problems they encountered, but haven't heard back, yet. Sadly, the code is closed-source so I haven't had any chance to look at it. If this inquiry leads nowhere, I might just have to monitor the bus messages of dropbox and see how they changed.
